dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - doxygen
      - graphviz
script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
  - doxygen Doxyfile
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T bulk_server-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb -urfrolov:$BINTRAY_API_KEY "https://api.bintray.com/content/rfrolov/otus/otus_homework_12/$TRAVIS_BUILD_NUMBER/bulk_server-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  - provider: pages
    skip-cleanup: true
    local_dir: html/
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
     branch: master